/**
 * EastCondos custom icon set — Modern Luxe hairline line-art (charcoal + amber accent),
 * generated to a consistent house style and served from /public/icons.
 *
 * 50 icons across 6 categories. Names + metadata are the SINGLE SOURCE OF TRUTH in
 * public/icons/icon-library.json; the typed list lives in ./ecIcons.ts, generated by
 * scripts/sync_icon_library.py (which also mirrors to Supabase bucket `icon-library` + table `cp_icons`).
 *
 * Each icon has two variants:
 *   variant="dark"  (default) — charcoal strokes, for CREAM / light backgrounds
 *   variant="light"           — cream strokes, for CHARCOAL / dark backgrounds (uses <name>-light.png)
 *
 * Decorative by default (aria-hidden); pass `alt` to make it meaningful.
 */
import type { EcIconName } from "./ecIcons";

export type { EcIconName, EcIconCategory, EcIconMeta } from "./ecIcons";
export { EC_ICONS, EC_ICON_NAMES, EC_ICONS_BY_CATEGORY } from "./ecIcons";

export default function EcIcon({
  name,
  size = 28,
  variant = "dark",
  alt = "",
  className = "",
}: {
  name: EcIconName;
  size?: number;
  /** "light" = cream strokes for dark/charcoal backgrounds; "dark" = charcoal strokes for cream. */
  variant?: "dark" | "light";
  alt?: string;
  className?: string;
}) {
  const file = variant === "light" ? `${name}-light` : name;
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={`/icons/${file}.png`}
      alt={alt}
      aria-hidden={alt === "" ? true : undefined}
      width={size}
      height={size}
      loading="lazy"
      className={className}
      style={{ width: size, height: size, objectFit: "contain" }}
    />
  );
}
