import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "HDB-Condo Meter Planner Disclaimer – eastcondos.sg",
  description:
    "Disclaimer for the HDB-Condo Meter Planner tool on EastCondos.sg. Important information regarding estimates and financial advice.",
};

export default function DisclaimerMeterPlannerPage() {
  return (
    <div>
      <div className="bg-sage-dark py-16 text-center">
        <h1 className="text-3xl md:text-4xl font-bold text-white">
          HDB-Condo Meter Planner Disclaimer
        </h1>
        <p className="text-gray-300 mt-3 text-lg">
          Please read this before using the planner
        </p>
      </div>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <div className="prose prose-navy max-w-none space-y-8 text-body leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-navy mb-4">
              1. No Financial Advice
            </h2>
            <p>
              The HDB-Condo Meter Planner (the &ldquo;Planner&rdquo;) provided
              on eastcondos.sg is for informational and educational purposes
              only. The results, calculations, and content generated by the
              Planner do not constitute financial, investment, legal, or tax
              advice.
            </p>
            <p className="mt-3">
              You should not rely solely on the Planner for making any financial
              decisions. We strongly stress the importance of consulting with qualified
              professionals—including licensed financial advisors, bankers,
              lawyers, and tax consultants—to obtain advice tailored to your
              specific situation before proceeding with any property transaction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-navy mb-4">
              2. Estimates and Projections Only
            </h2>
            <p>
              All figures, amounts, and timelines presented by the Planner are
              estimates based on the inputs you provide and certain assumptions
              (e.g., prevailing interest rates, current government policies, and
              market trends). These assumptions may not reflect your actual
              circumstances or future market conditions.
            </p>
            <p className="mt-3">
              Actual loan amounts, CPF usage, cash outlay, and affordability may
              vary significantly due to factors such as credit history, bank
              valuations, and regulatory changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-navy mb-4">
              3. Policy and Market Changes
            </h2>
            <p>
              Real estate regulations, tax laws (including ABSD and SSD), and
              banking policies in Singapore are subject to change. While we
              strive to keep the Planner updated, EastCondos.sg makes no
              representations or warranties regarding the accuracy,
              completeness, or timeliness of the information provided by the
              tool.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-navy mb-4">
              4. Limitation of Liability
            </h2>
            <p>
              By using the Planner, you acknowledge and agree that EastCondos.sg
              and its contributors shall not be held liable for any direct,
              indirect, incidental, or consequential damages or losses arising
              from your use of or reliance on the Planner. You assume full
              responsibility for any decisions you make based on the information
              provided.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
