import type { Metadata } from "next";
import { Card, CardContent } from "@/components/ui/Card";

export const metadata: Metadata = {
  title: "HDB-Condo Meter Planner Disclaimer – eastcondos.sg",
  description:
    "Disclaimer for the HDB-Condo Meter Planner tool on EastCondos.sg. Important information regarding estimates and financial advice.",
};

export default function DisclaimerMeterPlannerPage() {
  return (
    <div className="bg-cream min-h-screen">
      {/* Hero Section */}
      <div className="bg-navy relative overflow-hidden py-20 text-center">
        <div className="absolute inset-0 bg-[url('/noise.png')] opacity-10 mix-blend-soft-light"></div>
        <div className="relative z-10 max-w-4xl mx-auto px-4">
          <h1 className="text-4xl md:text-5xl font-serif font-bold text-white mb-4 animate-fade-in-up">
            HDB-Condo Meter Planner Disclaimer
          </h1>
          <p className="text-gray-300 text-lg md:text-xl font-light tracking-wide animate-fade-in-up delay-100">
            Important information regarding your use of this tool.
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12 -mt-10 relative z-20">
        <Card variant="glass" className="animate-fade-in-up delay-200">
          <CardContent className="prose prose-slate max-w-none p-8 md:p-12 space-y-8">
            <section>
              <h2 className="text-2xl font-serif font-bold text-navy mb-4 border-b-2 border-gold/20 pb-2 inline-block">
                1. No Financial Advice
              </h2>
              <p className="text-body leading-relaxed">
                The HDB-Condo Meter Planner (the &ldquo;Planner&rdquo;) provided
                on eastcondos.sg is for <strong>informational and educational purposes
                  only</strong>. The results, calculations, and content generated by the
                Planner do not constitute financial, investment, legal, or tax
                advice.
              </p>
              <div className="bg-sage-light p-4 rounded-lg border-l-4 border-sage mt-4">
                <p className="text-sage-dark text-sm font-medium m-0">
                  <strong>Important:</strong> You should not rely solely on the Planner for making any financial
                  decisions. We strongly stress the importance of consulting with qualified
                  professionals—including licensed financial advisors, bankers,
                  lawyers, and tax consultants.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-serif font-bold text-navy mb-4 border-b-2 border-gold/20 pb-2 inline-block">
                2. Estimates and Projections Only
              </h2>
              <p className="text-body leading-relaxed">
                All figures, amounts, and timelines presented by the Planner are
                estimates based on the inputs you provide and certain assumptions
                (e.g., prevailing interest rates, current government policies, and
                market trends). These assumptions may not reflect your actual
                circumstances or future market conditions.
              </p>
              <p className="text-body mt-3 leading-relaxed">
                Actual loan amounts, CPF usage, cash outlay, and affordability may
                vary significantly due to factors such as credit history, bank
                valuations, and regulatory changes.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-serif font-bold text-navy mb-4 border-b-2 border-gold/20 pb-2 inline-block">
                3. Policy and Market Changes
              </h2>
              <p className="text-body leading-relaxed">
                Real estate regulations, tax laws (including ABSD and SSD), and
                banking policies in Singapore are subject to change. While we
                strive to keep the Planner updated, EastCondos.sg makes no
                representations or warranties regarding the accuracy,
                completeness, or timeliness of the information provided by the
                tool.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-serif font-bold text-navy mb-4 border-b-2 border-gold/20 pb-2 inline-block">
                4. Limitation of Liability
              </h2>
              <p className="text-body leading-relaxed">
                By using the Planner, you acknowledge and agree that EastCondos.sg
                and its contributors shall not be held liable for any direct,
                indirect, incidental, or consequential damages or losses arising
                from your use of or reliance on the Planner. You assume full
                responsibility for any decisions you make based on the information
                provided.
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
